// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjqhepntrlgfgpfhpvom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqcWhlcG50cmxnZmdwZmhwdm9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MjY2MDUsImV4cCI6MjA2MTIwMjYwNX0.S5MdoJyi-xh3aE7hQkciC4haIT_8ObZqAER9RK2iU_w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);